sms:
  provider:
    selected: aliyun # aliyun、ctyun，可支持多选, 多选格式为 aliyun,ctyun
  providers:
    aliyun:
      weight: 10
    ctyun:
  # 失败重试机制
  retry:
    enabled: # 默认 false 关闭
    limit:  # 立即重试次数，不设置默认为3次
    maxRetryTimes: #最大重试次数
    fixedDelay: # 默认5000 单位ms，每隔多少时间重试一次


load:
  balance:
    isEnabled: true # true 开启负载均衡 false 关闭，此时只根据以下配置中按优先级加载，如果A服务商不可用，则切换至B服务商
    balancer: random # random roundRobin Weighted

queue:
  enabled: true
  kafka:
    topic:
    bootstrapAddress:

monitor:
  enabled: true # 是否开启监控功能
  dataUrl: http://localhost:8000/api/v1/monitor # 监控数据上传地址
  apiKey: YOUR_API_KEY # 可能的认证信息

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: 'prometheus'
